import { ChangeEvent, ReactElement, ReactNode } from "react"

export type Params = {
    [key: string]: any
}

export interface ColumnsProps {
    field: string,
    headerName: string,
    width: string | number,
    renderCell?: (params: Params, action: (e?: ChangeEvent<HTMLInputElement>, user?: User) => void) => ReactNode | ReactElement
    actionsItem?: (params: Params, action: (e?: ChangeEvent<HTMLInputElement>, user?: User) => void) => ReactNode | ReactElement
}

export interface User{
    auth0_id?: string,
    birthday?: string,
    email?: string,
    id?: string,
    image?: string,
    is_admin?: boolean,
    language?: string,
    lastname?: string,
    middlename?: string,
    name?: string,
    phone?: string,
    second_lastname?: string,    
    timezone?: string
}

export interface TableFooterProps <Data> { 
    callBack: (number: number) => void,
    range: number[],
    setPage: any,
    page: number,
    slice: Data[],
    totalItems: number,
    rowsPerPage:number,
    iconRow?: any
}

// Generated by https://quicktype.io

export interface UserTable {
    data: User;
}

export interface Image {
    file_name:  string;
    updated_at: string;
}
