// Generated by https://quicktype.io

export interface Styles {
    fonts:     Fonts;
    fontSizes: { [key: string]: string };
    colors:    { [key: string]: string };
    spaces:    { [key: string]: string };
}

export interface Fonts {
    "--fontA": string;
    "--fontB": string;
}